Migratation to jina3
jina-ai/executor-image-torch-encoder pull request #30
Opened 2022-01-25 10:03 UTC by samsja

DO NOT MERGE before :
* merging https://github.com/jina-ai/executor-image-torch-encoder/pull/29 into main
* changing back the cicd to point to the master branch of the workflow-executors repo 
* changing the dockerfilegpu to use the last official jina release

2022-01-27 06:21 UTC, nan-wang requested changes, later dismissed

2022-01-27 06:21 UTC, nan-wang commented on executor/torch_encoder.py
> +        traversal_paths: Tuple = '@r',
```suggestion
        traversal_paths: str = '@r',
```

2022-01-28 08:53 UTC, JoanFM approved these changes

2022-02-01 15:38 UTC, samsja commented
related to https://github.com/jina-ai/internal-tasks/issues/382

2022-02-11 13:05 UTC, JohannesMessner approved these changes

2022-02-11 13:08 UTC, merged